// MENU
export const SET_MENU = 'SET_MENU';

// CART
export const SET_CART = 'SET_CART';
export const SET_SUBTOTAL = 'SET_SUBTOTAL';
export const SET_TAX = 'SET_TAX';
export const SET_TOTAL = 'SET_TOTAL';

// APP LAYOUT STATES
export const NAME_CHANGE ='NAME_CHANGE';
export const TOGGLE_LEFT_NAV = 'TOGGLE_LEFT_NAV';
export const TOGGLE_RIGHT_NAV = 'TOGGLE_RIGHT_NAV';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const SET_MODAL_ID = 'SET_MODAL_ID';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const FIX_HEIGHT = 'FIX_HEIGHT';
export const INIT_TYPES_ARRAY = 'INIT_TYPES_ARRAY';
export const SET_EDIT_ID = 'SET_EDIT_ID';
export const TOGGLE_EDIT = 'TOGGLE_EDIT';
export const SET_FLIPPED_RIGHT = 'SET_FLIPPED_RIGHT';
export const SET_FLIPPED_LEFT = 'SET_FLIPPED_LEFT';
export const TOGGLE_SUMMARY_MODAL = 'TOGGLE_SUMMARY_MODAL';
export const TOGGLE_WAITING_ROOM = 'TOGGLE_WAITING_ROOM'
export const TOGGLE_STILL_THERE = 'TOGGLE_STILL_THERE'

//APP WORKFLOW 
export const SET_ORDER_ID = 'SET_ORDER_ID';
export const SET_CUSTOMER_ID = 'SET_CUSTOMER_ID';
export const SELECT_PROPERTY = 'SELECT_PROPERTY';
export const SET_CUSTOMER_NAME = 'SET_CUSTOMER_NAME';
export const SET_SELECTED_PROPS = 'SET_SELECTED_PROPS';
export const SET_SETTLED = 'SET_SETTLED';
export const SET_ALL_SETTLED_TRUE = 'SET_ALL_SETLLED_TRUE';
export const SET_ALL_SETTLED_FALSE = 'SET_ALL_SETLLED_FALSE';
export const SET_SENT_TRUE = 'SET_SENT_TRUE';
export const SET_SENT_FALSE = 'SET_SENT_FALSE';
export const SET_ENTERED = 'SET_ENTERED';
export const SET_JUST_ENTERED = 'SET_JUST_ENTERED';
export const SET_FIRST_SETTLE = 'SET_FIRST_SETTLE';